### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by patrickberkeley** [ryanb/letter_opener#1]
I followed the instructions (1. Add the gem to Gemfile, run bundle, 2. Set delivery method to :letter_opener in development.rb) and nothing happens when a mail is sent. I scanned through the logs and it looks normal. Tried this with both pow and normal WEBrick server.

Thanks! This looks awesome.

**Comment by moeyster** [comment]
Hi guys, 

I'm on ubuntu 14.04 lts and im getting a similar issue. my tmp file has the emails but it dosent open up in new tabs on browser. heres the error i got from the log:

[0417/123858:ERROR:nss_util.cc(94)] Failed to create /home/moeyster/.pki/nssdb directory.

here are my gem versions: 

launchy (2.4.3)
letter_opener (1.3.0)

tried the code:
file = File.expand_path(Dir["tmp/letter_opener/1424839210_a3ea6cb/rich.html"].first)
Launchy.open("file://#{file}")

and it works, but when emails are sent through the app, nothing opens in the browser. the emails worked before, and it worked pretty well. untill one day it just stopped. i havent changed anything in the app however i did install an update on my OS. any suggestions?

**Comment by diegodesouza** [comment]
I'm having the same problem as everyone else was having

```letter_opener 1.4.1
launchy 2.4.3```

```config.action_mailer.default_url_options = { :host => 'localhost:3000' }
  config.action_mailer.delivery_method = :letter_opener```

What am i missing?

**Comment by looser990** [comment]
Hello guys, not sure if I'm just stupid or maybe other people also got problem with this. But I found out that problem with my project is actually not in `letter_opener` but in rubymine. Not sure yet how or even possible to fix it.

**Comment by jgrosso-dynamynd** [comment]
@looser990 Do you mean if you develop an application with Rubymine, if you run it from Rubymine, ...?

**Comment by looser990** [comment]
@jgrosso-dynamynd Yes. I'm developing with Rubymine and when I start application in development mode using Rubymine it does not open mails. If I run application from terminal it works as expected.

**Comment by mhassaan** [comment]
Hi guys , I have integrated this gem in my application successfully. But the problem is nothing shows up in my browser. Moreover, i cant see any folder ''letter_opener" under tmp directory. The version of gems are as follows:
`letter_opener-1.4.1`
`launchy-2.4.3`

One more thing , gem works if I add this line `config.action_mailer.perform_deliveries = true` to my development.rb whereas it is not mentioned in the documentation. But still nothing shows up in my browser. What am i missing?

**Comment by nashby** [comment]
@mhassaan hey, what OS are you using?

**Comment by olliekav** [comment]
I've had this issue using Ruby-2.3.1 and Rails 4.2.3. The only way I could get it to work was adding...

`config.action_mailer.default_url_options = { host: ENV["DOMAIN"] }`

**Comment by mhassaan** [comment]
@nashby I am using OSX El Captain.

**Comment by TiSer** [comment]
I have the same problem, Chrome and OS X El Cap.
"perform_deliveries" doesn't help.

**Comment by gafrom** [comment]
The same problem, FireFox, OS X EI Capitan, Rails 5.
No `tmp/letter-opener` folder whatsoever.
`letter_opener v1.4.1`
`launchy v2.4.3`

Any ideas what I may be missing?
@mhassaan any luck with the issue?

**Comment by mhassaan** [comment]
@gafrom which version of ruby are you using ?
My configuration is like this and luckily its working with this configuration.
`Ruby version: 2.1.2p95`
`Rails version: 4.1.1`
In development.rb i have added this line 
`config.action_mailer.delivery_method = :letter_opener`

**Comment by gafrom** [comment]
@mhassaan I'm running on `Ruby 2.3.1`.
Added all what I coould to development.rb:
` config.action_mailer.delivery_method = :letter_opener`
`config.action_mailer.perform_deliveries = true`
and still no luck...

**Comment by mhassaan** [comment]
@gafrom I am quite sure you are missing something. I just tested this gem with following version
`ruby 2.2.1p85` 
`Rails 4.2.1`
And after bundle install, I added following two lines 
`config.action_mailer.perform_deliveries = true`
`config.action_mailer.delivery_method = :letter_opener`

Restart the server And it worked fine.  To be sure just check are you actually delivering emails or not . I mean may be you are forgetting to add 'deliver_now' when you try to send emails.

Like this,
`ModelMailer.welcome_email(model_instance).deliver_now`

**Comment by gafrom** [comment]
Sorry for a delay,

@mhassaan yes, you're right, I used to enqueue mail jobs via `deliver_later` using Resque adapter which in turn failed to work properly for some reason. When I changed adapter to `:inline` mails started pouring up into browser smoothly 👍 .

Thanks.

**Comment by mhassaan** [comment]
@gafrom great to know that it works. You are welcome (y) .

**Comment by railsfactory-madhusudhan** [comment]
I am also facing issue with letter_opener opening in browser. App has tmp/letter_opener folder and files inside that. If I do Launchy.open("#{Rails.root}/tmp/letter_opener/1479795772_170cb89/rich.html") it is opening in browser, just it is not triggering when it is called on deliver_now. 

In development.rb
config.action_mailer.delivery_method = :letter_opener
config.action_mailer.perform_deliveries = true
config.action_mailer.raise_delivery_errors = false

**Comment by Ingosmar89219** [comment]
comunity please help me :(. 'letter_opener' works in ubuntu but in windows open a file with name "rich.html" in the editor sublime text but it should open in the browser, someone know why? thanks a lot

**Comment by Mikopet** [comment]
@Ingosmar89219 I dont know why this happens, but at me it opens the letter with **wine notepad** on ubuntu! I didnt even know I have that :D

**Comment by acosonic** [comment]
Yeah I can confirm also works for me on ubuntu, does not work for me on Windows nor OSX ...

Launchy works well though.

**Comment by Kadaaran** [comment]
Same here. I followed exactly  the README and there is no new tab opening when I send an email and the tmp files are not created. Any idea ?
Ruby version: ruby 2.4.2
Rails version: 5.0.7

**Comment by berberecho5** [comment]
I had the same issue. I resolved it changing the ownership of letter_opener folder. It turns out that when I cloned the repo a root ownership was set to this and other tmp/ folders. Changing the ownership to your will fix the issue.

**Comment by szpasztor** [comment]
I had the same issue. Making sure `from` and `reply_to` options were filled fixed it.
```rb
default from: "test@test.com", reply_to: "test@test.com"
```

**Comment by microspino** [comment]
Just in case someone is still unable to see his/her email in the browser as per @mhassaan  suggestion i solved by doing this:

`_mailer = MyMailer.send_quote(@cart)
 Rails.env.production? ? _mailer.deliver_later : _mailer.deliver_now`

**Comment by computalya** [comment]
the reason why it didn't work on my local machine was, that I had a space in my applications path.

`~/workspace/demo applications/demoapp`

it worked when I moved  the demo app into `/tmp`

**Comment by daveomcd** [comment]
@computalya thanks! this was my problem too.  I changed my projects parent directory from "Rails Projects" to "rails_projects" and then it worked.  Previously, I was getting an error message in console saying... 

`The file /Users/david/Documents/Rails Projects/bmoretasty/file:/Users/david/Documents/Rails Projects/bmoretasty/tmp/letter_opener/1625881276_7074199_0cbffbc/rich.html does not exist.`

**Comment by dropifybrownish** [comment]
@patrickberkeley https://stackdev.space/questions/rails-passing-json-data-to-controller-results-in-an-evaluation-of-nil
