### ISSUE TITLE
Letter Opener doesn't seem to support deliver_later?

### ISSUE THREAD

**Issue by cassidyclawson** [ryanb/letter_opener#102]
In Rails 4.2 with ActiveJob on Sidekiq in development mode, Letter Opener does not open emails in the browser when using deliver_later!. deliver_now is working great. 

I'm uncertain if this a known issue or a bug in my setup. 

Also - thanks for the great gem. Makes development of emails so much nicer.

**Comment by nashby** [comment]
@cassidyclawson hey, the only way of fixing it is to configure your Sidekiq to perform jobs inline (you can add some intializer with ```Sidekiq::Testing.inline!``` and use it in dev environment). Not really sure you want all your jobs to be inline in the development environment but as I can see it's the only solution. Probably we can override Rails's deliver_later method but I'm not really sure it's a good idea.

**Comment by chrisnicola** [comment]
Curious why this doesn't work. I'm pretty sure it used to work with Sidekiq just fine. Is this something to do with ActiveJob?

**Comment by chrisnicola** [comment]
FYI this suggestion doesn't work.

Also afaik ActiveJob is just creating a job on the Sidekiq worker to call `deliver_now` again so I don't see why it wouldn't get sent to letter_opener at that point.

**Comment by chrisnicola** [comment]
For anyone reading this, I'm an idiot and something internal was preventing e-mailing. Also for the record letter_opener works just fine with `deliver_later`.
