### ISSUE TITLE
Working on remote server ?

### ISSUE THREAD

**Issue by Startouf** [ryanb/letter_opener#103]
Is this gem supposed to work on remote servers ? (ie: rails app @ my-host.com, browser triggering email @ random_ip)

If yes, then I'm having problems... If no, could be a feature ? 

(Works well on my computer, not with a capistrano deployment (with a development-like stage)

**Comment by nashby** [comment]
@Startouf no, it's not supposed to work remotely. Please check https://github.com/ryanb/letter_opener#remote-alternatives
