### ISSUE TITLE
Letter-opener sends email event if there is no recipient

### ISSUE THREAD

**Issue by Swati24** [ryanb/letter_opener#106]
It becomes unreliable if this gem doesn't reciprocate SMTP behavior. Not exactly but letter_opener should raise some kind of error if there is no recipient to send email as corresponding to SMTP:

An SMTP To address is required to send a message. Set the message smtp_envelope_to, to, cc, or bcc address...

**Comment by nashby** [comment]
@Swati24 hey, thank you for the great idea, I really liked it so I pushed these changes to the master branch. Could you please test it in you application?

**Comment by nashby** [comment]
@Swati24 hey, just letting you know that I released a new 1.4.0 version with this feature. Could you please test it and report any issues back? Thanks!
