### ISSUE TITLE
Plain text emails contain literal <base target="_top">

### ISSUE THREAD

**Issue by cobyism** [ryanb/letter_opener#107]
It looks like the change made in 615ce8fa03a14ddd9281012fb91b6a47cf7e7447 to fix #105 means that plain-text email previews now contain `<base target="_top">` as part of the preview’s rendered output.

![2015-05-20 at 2 49 pm](https://cloud.githubusercontent.com/assets/296432/7727328/f79ef14c-feff-11e4-8841-e4991fe12bc2.png)

Is this intended? Should this be conditionally prepended to only the HTML part of previews instead?

/cc @nashby #105

**Comment by nashby** [comment]
@cobyism yeah, it wasn't intentional, sorry. Would you be so kind to send a pull request fixing it as you suggested? Thanks!

**Comment by cobyism** [comment]
Sure, I can take a stab at it.

**Comment by jankeesvw** [comment]
I am seeing the same issue with version 1.4.0.

**Comment by cobyism** [comment]
@jankeesvw I’ve got a fix waiting in #108, so hopefully that can be merged in and a new version released soon.
