### ISSUE TITLE
Request - remove message header

### ISSUE THREAD

**Issue by cba7** [ryanb/letter_opener#111]
It would be great if as a letter_opener option, emails could be opened in the browser without the message header, or indeed without the id="container" div added.

Just open the exact message that would be sent by rails.

Thanks!

**Comment by nashby** [comment]
Hey guys, I know it's been awhile but can you check this brunch https://github.com/ryanb/letter_opener/pull/143? With it it's possible to set `light` version of the mail template without any styling. You can set it as:

```
LetterOpener.configure do |config|
  config.message_template = :light
end
```

**Comment by nashby** [comment]
It should be possible to do with master branch now.
