### ISSUE TITLE
Impossible to view emails in any version of Internet Explorer.

### ISSUE THREAD

**Issue by schesis** [ryanb/letter_opener#112]
The use of an iframe with the srcdoc attribute makes it impossible to use letter_opener for testing HTML email in Internet Explorer, no version of which supports the attribute:

http://caniuse.com/#feat=iframe-srcdoc

**Comment by nashby** [comment]
@schesis hey, thanks for pointing out to this issue. I think I managed to fix it with a srcdoc shim for IE. Not really sure it's the best solution but right now I can't think about better one. Can you please test master branch and see if it works for you? Thanks!

**Comment by schesis** [comment]
@nashby yes, with the shim it works across IE6-11. Thanks!
