### ISSUE TITLE
letter_opener for mailcatcher using devise

### ISSUE THREAD

**Issue by hemashree** [ryanb/letter_opener#114]
Hi ryanb,
 
The letter_opener will working for normal action_mailer method. When I am using the same for mailcatcher with devise authentication it is not working. I am not getting the popup also.Will you please help me to solve this problem.Thanks in advance.

**Comment by nashby** [comment]
@hemashree hey, not really sure what you mean. why do you need both letter_opener and mailcatcher at the same time? They both allow you to do one thing: catch and show sent email.

**Comment by hemashree** [comment]
Thanks for your response @nashby. Leave about mailcatcher thing. Can we use the letter_opener for devise authentication.

**Comment by nashby** [comment]
@hemashree don't think there should be some extra configuration for devise. Can you please create a sample application that reproduces your issue? Thanks!
