### ISSUE TITLE
Gmail - like preview?

### ISSUE THREAD

**Issue by jponc** [ryanb/letter_opener#115]
Hi guys, thanks for this fantastic gem for previewing the emails locally. I just have a feature request, not high priority though, but it would be great to mimic the way Gmail renders the email (like removing some of the css that's not allowed and etc)

Problem is, it's properly working in my local but when I send a live email to my Gmail account, it just blows everything because Gmail has a lot of restrictions.

Cheers!

**Comment by nashby** [comment]
@jponc hey, thank for this feature request but when I was starting helping @ryanb with this gem I was told to keep it as simple as possible and adding something like Gmail render emulator will complicate this project a lot. Maybe in the future @ryanb will consider adding something like that. Thanks again!
