### ISSUE TITLE
Add option to specify the App to open the HTML mail

### ISSUE THREAD

**Issue by caesarsol** [ryanb/letter_opener#118]
My OS X is configured to open .html files with Sublime Text, but I would like to open the e-mails in Chrome.

I've eamined the Lauchy configurations, but there's not a global config file and the Lauchy command in letter_opener is hardcoded: https://github.com/ryanb/letter_opener/blob/master/lib/letter_opener/delivery_method.rb#L24

Is there something I missed? Can I submit a :octocat: PR? :)

**Comment by nashby** [comment]
@caesarsol hey, can't you use launchy's global config using `ENV['LAUNCHY_APPLICATION']`?

**Comment by caesarsol** [comment]
hey @nashby, thanks! 
I've never found documentation of that env var, will try it asap.

could be useful to include in the README?

**Comment by nashby** [comment]
@caesarsol sure, can you please make a PR?
