### ISSUE TITLE
Installed but not installed

### ISSUE THREAD

**Issue by henrikj242** [ryanb/letter_opener#127]
Hi,
I was excited to check out this gem, but even after installing it in my rails 4 project and changing the configuration to use letter_opener as the delivery method, there is no initializer file and mails are not being written to the tmp-dir.

What could I be missing?

I am using sidekiq/redis as the queue. Should that cause any issues?

thx

**Comment by henrikj242** [comment]
Ah, please ignore - I had not launched sidekiq. It seems to work now :)

**Comment by nashby** [comment]
Cool!
