### ISSUE TITLE
(Gmail) Actions 

### ISSUE THREAD

**Issue by ivdma** [ryanb/letter_opener#128]
I am developing an application which is heavily based on sending email messages along with [(gmail) actions](https://developers.google.com/gmail/markup/overview#gmail_actions) which I wouldn't rather test by sending actual emails to Gmail. 
I understand that you guys [want to keep this gem simple](https://github.com/ryanb/letter_opener/issues/115). But is there a way to make some kind of addition to this gem that would render actions based on provided markup?
If I would make a PR for this, would you merge it, or would you consider this feature out of scope of letter_opener?

Thanks, Ivan

**Comment by nashby** [comment]
@ivdma hey, sorry for the late reply but I think it's better to keep that as separate project (probably as extension to `letter_opener` if that's possible). If you do it you can totally send a pull request with a link to your extension so we can put it in README. Cheers!
