### ISSUE TITLE
support for nginx in development

### ISSUE THREAD

**Issue by railsfactory-madhusudhan** [ryanb/letter_opener#134]
letter opener not opening in browser in Nginx in development environment, if I run on webrick it is opening mail on browser. I have many applications that interchange data, so I have nginx running rather than running each app on different ports in webrick. Question is, will letter opener support in nginx server in development environment?

I am running on Ubuntu 14.04.
ruby - 2.3.1
rails - 4.2.5.1
letter_opener - 1.2.0

In Mac it is working fine with nginx server.

**Comment by railsfactory-madhusudhan** [comment]
More info from gem on how it looks like

cmd =  #<Launchy::Argv:0x007f7e726a7690 @argv=["xdg-open"]>
args = [["file:////home/username/projects/simple_app/tmp/letter_opener/1479896686_41ee911/rich.html"]]

shell_commands( cmd, *args ) = ["xdg-open", "file:////home/username/projects/simple_app/tmp/letter_opener/1479896686_41ee911/rich.html"]

When this line executes exec( *shell_commands( cmd, *args )) it does nothing and it doesn't complete the call, then the process is detached. Is there anything nginx is holding up?

**Comment by nashby** [comment]
@railsfactory-madhusudhan did you try to run `xdg-open` from console yourself?

**Comment by railsfactory-madhusudhan** [comment]
@nashby yes I tried and it opened from console. I tried with demo app with webrick server and it's working fine, only change here is I'm using nginx server for development environment.

**Comment by nashby** [comment]
@railsfactory-madhusudhan hey, have you figured that out?
