### ISSUE TITLE
Rails 5.x Support

### ISSUE THREAD

**Issue by lucianosousa** [ryanb/letter_opener#141]
Do you guys have plans to update the gem to be compatibe with Rails 5 series?

**Comment by nashby** [comment]
@lucianosousa do you have any particular issues with Rails 5? Can you please describe what's wrong? And it would be nice if you could push some sample application that fails so we can dig into it!

**Comment by lucianosousa** [comment]
@nashby I'ts in a private repo. But, the problem is that any email is rendered to me here.
Do you know if the gem is compatible with rails5? I can take a look on this weekend to see what can we do reproduce here

**Comment by nashby** [comment]
@lucianosousa nope, I don't use it with Rails 5 ATM. So please feel free to send sample application that reproduces your issue and we fix it together!

**Comment by nisshiee** [comment]
In my project, letter_opener runs with rails 5.0.1 but occurs error with rails 5.0.2.

```
Devise::Mailer#reset_password_instructions: processed outbound mail in 13.2ms
Completed 500 Internal Server Error in 862ms (ActiveRecord: 46.5ms)
RuntimeError (Invalid delivery method :letter_opener):
```

**Comment by nisshiee** [comment]
Sorry, this simple test application works correctly...
https://github.com/nisshiee/letter_opener_test

I will investigate the error before project

**Comment by lucianosousa** [comment]
sorry being late guys. Yes, I did few tests here again and seems everything works correct
