### ISSUE TITLE
1.6.0 adds requirement for to address

### ISSUE THREAD

**Issue by axlekb** [ryanb/letter_opener#153]
I recently upgraded from 1.5.0 to 1.6.0 and `letter_opener` now fails to launch emails without a `to` address.  It is valid to send email with only `cc` or `bcc`. These emails previously did not fail and should raise errors.  

```ruby
# lib/letter_opener/delivery_method.rb#29
if !mail.to || mail.to.empty?
  raise ArgumentError, "SMTP To address may not be blank"
end
```

**Comment by nashby** [comment]
@axlekb hi! Thanks, good catch. I've fixed that in master.

**Comment by axlekb** [comment]
Thank you!!!

**Comment by yanghoxom** [comment]
for someone who was using the newest version but still can not raise the crash on local environment
you can recheck the config to make sure you added this
```
config.action_mailer.raise_delivery_errors = true
```
