### ISSUE TITLE
image not loading

### ISSUE THREAD

**Issue by faizaankhan** [ryanb/letter_opener#154]
Letter opener never shows the images (assets) in the development environment. Is there some change required in the configuration?

**Comment by nashby** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by faizaankhan** [comment]
Add in your development.rb
```
config.action_controller.asset_host = "http://localhost:3000"
config.action_mailer.asset_host     = "http://localhost:3000"
```
The question was very specific, wanting a sample application for configuration related question is not so cool.

**Comment by Salomanuel** [comment]
how can this be accomplished on Staging env as well?
