### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by blindMoe** [ryanb/letter_opener#192]
I can see that there is progress that has been made on the master branch but I don't see new versions being released for the gem.  Are there any plans to update the version number and push up to the gem repo so people receive the updates?  1.7.0 is probably what most people have in the Gemfiles but until a new version is release they won't get any of the updates

**Comment by nashby** [comment]
Hey @blindMoe! Could you please test master branch and see it works for you? I fixed some issues and will try to release soon and your testing will be really appreciated!

**Comment by agrberg** [comment]
I can confirm all 68 tests passing on Ruby 3.0.3 with the following `Gemfile.lock` as well as passing within my Rails 7 app 🎉 

```
PATH
  remote: .
  specs:
    letter_opener (1.7.0)
      launchy (>= 2.2, < 3)

GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    diff-lcs (1.5.0)
    launchy (2.5.0)
      addressable (~> 2.7)
    mail (2.6.6)
      mime-types (>= 1.16, < 4)
    mime-types (3.4.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2022.0105)
    public_suffix (4.0.6)
    rake (13.0.6)
    rspec (3.10.0)
      rspec-core (~> 3.10.0)
      rspec-expectations (~> 3.10.0)
      rspec-mocks (~> 3.10.0)
    rspec-core (3.10.1)
      rspec-support (~> 3.10.0)
    rspec-expectations (3.10.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.10.0)
    rspec-mocks (3.10.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.10.0)
    rspec-support (3.10.3)

PLATFORMS
  x86_64-darwin-21

DEPENDENCIES
  letter_opener!
  mail (~> 2.6.0)
  rake
  rspec (~> 3.10.0)

BUNDLED WITH
   2.2.32
```
