### ISSUE TITLE
[Q] Do you like to integrate

### ISSUE THREAD

**Issue by TomFreudenberg** [ryanb/letter_opener#195]
Hi @ryanb 

I am wondering if you like to integrate [MidiSmtpServer](https://github.com/4commerce-technologies-AG/midi-smtp-server) into your [letter_opener](https://github.com/ryanb/letter_opener)?

There is an example for a [Slack Router](https://github.com/4commerce-technologies-AG/midi-smtp-server/tree/master/cookbook/recipe-slack) and it is also very easy to integrate a SMTP service with that.

Looking forward to your feedback.

Cheers
Tom

**Comment by nashby** [comment]
Hey @TomFreudenberg. We don't have any plans for that since we want to keep letter_opener as simple as possible.

**Comment by TomFreudenberg** [comment]
Thanks for feedback Vasiliy @nashby
