### ISSUE TITLE
Unable to interpret 'file:///rich.html' as a path or URL

### ISSUE THREAD

**Issue by lmonica97** [ryanb/letter_opener#196]
Hi there, 

I'm getting the error: Unable to interpret 'file:///rich.html' as a path or URL. 

I've tried doing Launchy.open('file:///rich.html') and I get a bunch of Syntax Errors. However, when I copy the file path onto my browser, the file opens up fine.

Rails ver 6.1

**Comment by nashby** [comment]
Hey @lmonica97. What are the errors you get why you try Launchy.open?
