### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by phylor** [ryanb/letter_opener#198]
First of all, thank you for all the work, the regular commits, improvements and fixes and that you are still maintaining this very useful project! :muscle: 

The last release is from late 2018. Are you planning a new release any time soon? I'd really appreciate one to be able to move away from specifying `master` in the `Gemfile`, or not being able to profit from the improvements where that is not possible.

**Comment by nashby** [comment]
Hey @phylor. 1.8.0 has been released! Enjoy!

**Comment by phylor** [comment]
@nashby Awesome, thank you very much! :tada:
