### ISSUE TITLE
uninitialized constant LetterOpener with RSpec 3.11

### ISSUE THREAD

**Issue by lfloresPL** [ryanb/letter_opener#199]
Hi, I'm having this error with Rails 7.0.2.2, Ruby 3.1.0 and RSpec 3.11. I did all the configuration steps you list in the README.md, Rails server still able to run without problem, it is only in test, I tried adding the config lines to config/environments/test.rb with no succes
<img width="1418" alt="Screen Shot 2022-03-09 at 13 28 24" src="https://user-images.githubusercontent.com/99517772/157530270-e87dc421-6050-4425-af47-258b867abb85.png">
s

**Comment by nashby** [comment]
Hey, can you please create a sample app that reproduces this issue?

**Comment by lfloresPL** [comment]
Sorry, tried but not able to reproduce the issue with a simple demo app... Team leader just moved to other approach...
