### ISSUE TITLE
Launchy::CommandNotFoundError

### ISSUE THREAD

**Issue by PrathamMajithia** [ryanb/letter_opener#203]
I'm using Cloud9 VM unix based, and I have an app based on Rails 6.1.4 and using letter opener v1.8.1.

I get this error:
Launchy::CommandNotFoundError (Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new):  

I know in the description it asks to add the following commands, to resolve this issue.
LAUNCHY_DRY_RUN=true
BROWSER=/dev/null

But can someone please tell me where do I put this code? And adding BROWSER=/dev/null gives me an error invalid regex error.
Thanks in advance.

**Comment by nashby** [comment]
Hey, you can find how to set env variables [here](https://docs.aws.amazon.com/cloud9/latest/user-guide/env-vars.html) .
