### ISSUE TITLE
Is there a way to Rate Limit Emails

### ISSUE THREAD

**Issue by BakoviDagi** [ryanb/letter_opener#206]
We like to keep our development data matching prod as close as we can, but that means that when I click to send an email to all clients, it tries opening 5,000 tabs for me. Is there a way to limit how many emails of the same type open? Ideally I'd like to only open the first email per batch.

**Comment by nashby** [comment]
@BakoviDagi hey, unfortunately there's no way to rate limit emails. I think https://github.com/sj26/mailcatcher will be better for your needs since you can see all your emails in ui
