### ISSUE TITLE
subject is prepended with 'lots of' copies of the to address

### ISSUE THREAD

**Issue by koenhandekyn** [ryanb/letter_opener#214]
after migrating to latest rails and ruby we are noticing that the subject is prepended with an indeterministic but large amount of copies of the to address. see below picture. 

<img width="1467" alt="image" src="https://github.com/ryanb/letter_opener/assets/710262/d425a94e-7709-4b5d-a341-a1881488effe">

**Comment by nashby** [comment]
@koenhandekyn hey! Would it be possible for you to create a sample application that reproduces this issue?

**Comment by nashby** [comment]
I couldn't reproduce it in a sample app. It really looks like app specific issue, so I'm closing this. Let me know if you have a way to reproduce and I'll reopen it. Thanks!
