### ISSUE TITLE
Any thoughts on not requiring launchy?

### ISSUE THREAD

**Issue by epugh** [ryanb/letter_opener#215]
I run inside Docker, so I can't use the launchy capability, but I am still updating it periodically in my Gemfile.lock.  I do have the ENV variables to ignore it, but is there a way to just exclude it totally?   --> In looking this may NOT be how folks recommend gemfiles work!

**Comment by nashby** [comment]
Hey! Unfortunately, no, Launchy is a core dependency of this gem. Technically, we could make it optional, but since opening emails is the main idea behind this gem, we are going to keep it this way. Sorry!

**Comment by epugh** [comment]
That totally makes sense!   Thanks for taking the time to reply.
