### ISSUE TITLE
Persist letters on database

### ISSUE THREAD

**Issue by coorasse** [ryanb/letter_opener#221]
We have used letter_opener for many years and recently thought that it would be interesting to have a different "adapter" to allow persisting emails in the database instead of disk. This would allow us to solve the problem of improving letter_opener_web, which currently cannot be used on Heroku.
I believe this gem has the potential to become a really interesting alternative to external services like Mailtrap, but we need a good foundation, from letter_opener itself to be able to persist on database.
So my question here is: is there interest from the maintainers to approve PRs that go into that direction? 
I'd introduce an opt-in option to use the database for storing emails instead of disk.
I am a maintainer myself so I understand if the maintainers would not be willing to support this in the future.

Let me know your thoughts. ✌️

**Comment by nashby** [comment]
@coorasse hey! Persisting emails in the DB sounds like a good idea for some cases but it feels like a new/separate gem at this point. Let me know if you decide to build something like that so I could add it to README!

**Comment by coorasse** [comment]
@nashby done! https://github.com/coorasse/letter_thief
Since we persist them on database it can also be used "just" to log emails.
I added a small note in the credits since I was inspired by letter_opener. ❤
