### ISSUE TITLE
Letter opener does nothing

### ISSUE THREAD

**Issue by tyrw** [ryanb/letter_opener#67]
I have letter_opener 1.1.0, launchy 2.2.0, Rails 3.2.11.  I added the line to development.rb as suggested, but nothing happens and tmp/letter_opener is not created (even after restarting the server).

Logs look normal, and email works fine in production.  No popup blockers in place.  Any ideas why it's not popping the message into a new window?

**Comment by Startouf** [comment]
In my case it seems /environments/development.rb wasn't overriding correctly the delivery setting of environment.rb.
