### ISSUE TITLE
Invalid delivery method :letter_opener

### ISSUE THREAD

**Issue by sappapp** [ryanb/letter_opener#75]
I have set the following setting in development.rb
# Mailing Configuration Parameters

  config.action_mailer.delivery_method = :letter_opener
  ActionMailer::Base.perform_deliveries = true
  ActionMailer::Base.raise_delivery_errors = false

Yet I am still receiving an error. Do you have any suggestions?

**Comment by guinslym** [comment]
Thanks @theuri

**Comment by itsNikolay** [comment]
got the same error because I have deleted the gem from Gemfile, so add:
```ruby
# Gemfile
gem 'letter_opener'
```

**Comment by inix** [comment]
> rm -rf .bundle fixed it for me

This solution works for me.
